---
apiVersion: v1
kind: Service
metadata:
  name: explainerdashboarddemo
spec:
  type: LoadBalancer
  selector:
    app: explainerdashboarddemo
  ports:
  - port: 9050
    targetPort: 9050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explainerdashboarddemo
  labels:
    app: explainerdashboarddemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explainerdashboarddemo
  template:
    metadata:
      labels:
        app: explainerdashboarddemo
    spec:
      containers:
      - name: explainerdashboarddemo
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/home-credit-repo/explainerdashboarddemo:latest